import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, ViewController, ToastController } from 'ionic-angular';
import { TinderProvider } from '../../providers/tinder/tinder';
import { ImageProvider } from '../../providers/image/image';
import { Camera, CameraOptions } from '@ionic-native/camera';
import { Crop } from '@ionic-native/crop';

@IonicPage()
@Component({
  selector: 'page-register',
  templateUrl: 'register.html',
})
export class RegisterPage {

  private tinUser: any = {};
  profilePicture: any = "/9j/4AAQSkZJRgABAQEAZABkAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wgARCAHCAcIDASIAAhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAEDBAIFBv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIQAxAAAAH7MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4O2Ws3MA3sVhpVdnSJAAAAAAAAAAAAAAAAAAAAAAHFWQupEAAAAd8DTp83tfQcdgAAAAAAAAAAAAAAAAAADLZiAQAAAAAACd2Do9FEqAAAAAAAAAAAAAAAAAiaDLyIAAAAAAAABp1eb6KyAAAAAAAAAAAAAAAABh2+aAgAAAAAAAADdh0moKAAAAAAAAAAAAAAABVh15EAAAAAAAAAAXU9noBQAAAAAAAAAAAAAAAM2XVlQAAAAAAAAABMD00SoAAAAAAAAAAAAAAAGbLryIAAAAAAAAAAB6UxKgAAAAAAAAAAAAAADkz5hAAAAAAAAAAEwPTVWqAAAAAAAAAAAAAAA47g81MIAAAAAAAAAABp1U3KAAAAAAAAAAAAAAAB5/GjOgAAAAAAAAAAHodxKgAAAAAAAAAAAAAAAcef6eIpCAAAAAAAAAL69p2FAAAAAAAAAAAAAAAARIz5PS84gIAAAAAAAup1mgKAAAAAAAAAAAAAAAAAAw7spmCAAAAAAAN+H0VkAAAAAAAAAAAAAAAAAADjseYupQAAAAAAC3dn0KAAAAAAAAAAAAAAAAAAABXg9HzgEAAAAAd8bC6RQAAAAAAAAAAAAAAAAAAAOfO9HzgEAAAAAbcW1bgAAAAAAAAAAAAAAAAAAAAR5vo+cAgAAAADbi2rcAAAAAAAAAAAAAAAAAAAAcnGGytAAAAAAGnNJ6SuxQAAAAAAAAAAAAAAAABBMUZzTl5IAAAAAAABOnKPSnzb11uOwAAAAAAAAAAAAAVFvGWk0UQQAAAAAAAAAAABdSN1vmWLvUXEgAAAAAAAAFJbVmrLKxAAAAAAAAAAAAAAAAHXI13+b0vos95IAAAABBNdGctqEAAAAAAAAAAAAAAAAAAAAdcjZf5lq7nHYAAKicUQgAAAAAAAAAAAAAAAAAAAAAAAE68Y9Nm0qBxgvzoAAAAAAAAAAAAAAAAAAAAAAAAAA24uz0EF8/kQAAAAAAAAAAAAAAAAAAAAAAAAAADcxl5CAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//EACUQAAIBBAIDAQACAwAAAAAAAAECAwARQFASMiEwMRMgIhBBgP/aAAgBAQABBQL/AI0LAUZa/Rq5tXNq/Vq/Wv0WrjXlgtNIT6w7ChLV76p5Le9WK0rBtRI+CDYq3IaWRuIwlPEjzpWPI4cTaSU2XEBsdHIbtixm6biLRSdMaLtoZeuMnfQzY4+6GbczfNxL13ErY4+6A+BkI3Jc9uuRDoT9x4x/TQP3x166CUecf/WgYXXGiHnRSLY4gQmlXiNG0Y44UQ/tpj4ODF800nfBQWTTSjB+nTsOS4EYu+okWx98Q8ahhdfcq8jqT890XXUn57oumpPz3RdNSfnui6ak/PdF01MhsvuiOpJtTtyPuBsVYMNM0gFFi2CDall0d7UZaLE4oJFCWgwOcWAoy0TfKEhFBwcouBRkJzw5FCQHGMgFFydGGK0JRhNIBTOW04Yill9zOFpnLasMVpZAfVe1NLr1crQYN/NmC0zFtje1JJf+Lvxr7tEf/JPEE3O1jbkKlPnbKbNTeW24bxuL7r//xAAUEQEAAAAAAAAAAAAAAAAAAACQ/9oACAEDAQE/AVJ//8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAgEBPwFSf//EACIQAAAGAQQDAQAAAAAAAAAAAAABESFAUFEQMDFgYXCAIP/aAAgBAQAGPwL40cMWnI50chyOa9wzbfIerQrhCgtT+Ya0yxEpEzFXuZ0R9QKiKOVEVyXckjl1o5J9aOQVCvUFo1i8BKRvQpU5HcpdLmAufo5LlajIeE9I0Zg4ac4YPKzMxQO0bNIwe6YPdMMbbWDbD2SHz+fNqh6qFtvOiXJ+q//EACoQAAECBQMDBAIDAAAAAAAAAAEAESExQFBRMEFhcYGRECChsWDhgMHR/9oACAEBAAE/If4aT8v2i5/j1/AJsUP1EC4dUDyDzbxESg0DSciS/wBQsfuEABwXFqyk5RJJclzrEHHhAHHi0f2xoSPIJ7fcWaCCajKyRAARI2SQdOtI3va8oMGCEQ9jeeIUzBxCxEsCcIly9McAsRNThM3IsRwDmnNrESU6E3Nikp29i+RUCVhldbyAhs3pxcXNhJw4RLlzTuxcKIGe9gBwcXoBiGDUNBzGw/MqIOhYWwzpwHLBAMAxYX4U7vFY4MkaU3DuKAysZDhinogxFG4/As4ODFEMZybODFzGiYFnjdihAYGbQ+UJo4jaYSlQGbTBGGvCdt1IWmf01wEe5Nqm9Nf7LVM1/stUzX+y1TOmv9lqceYa87vtIAclgotttrkAEwnQJ7izyaJGIqEhOCxQJQ8oEEOC9iIA5LIYldT89qUq5Mj7e4UxPXTsjmVuSiE5PVT6Bb+xwarf3OApdBXy8uMFZ4pubcLf2GBY507IyEKBBiKGBzPCmRYYFnMxIBhCpy1ZlPC4YYtc4dlBTFpEAclgjGEIzb4JMIQ5e8bGeEQfwuIInBYoG0+3tAPJEknMTdH8+x9RlJEIUzdoIZPR8cbu3Hz6E65vA29PzN//2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAABAwwww84AAAAAAAAAAAAAAAAAAAAAAwwwwwww9wAAAAAAAAAAAAAAAAAEIwwwwwwwwwzAAAAAAAAAAAAAAAAABAwwwwwwwwwxwAAAAAAAAAAAAAAAAKQwwwwwwwww1wAAAAAAAAAAAAAAAAAwwwwwwwwww1yAAAAAAAAAAAAAAAACwwwwwwwwwww6AAAAAAAAAAAAAAABKwwwwwwwwww1yAAAAAAAAAAAAAAAFAwwwwwwwwwww6AAAAAAAAAAAAAAAAIwwwwwwwwwwx4AAAAAAAAAAAAAAAABAwwwwwwwwwyQAAAAAAAAAAAAAAAAECAwwwwwww0wAAAAAAAAAAAAAAAAAAAAwwwwwwwxAAAAAAAAAAAAAAAAAAAACwwwwwwwyAAAAAAAAAAAAAAAAAAAAKAwwwwww4AAAAAAAAAAAAAAAAAAAAKAwwwwwwAAAAAAAAAAAAAAAAAAAAACAwwwwwwgAAAAAAAAAAAAAAAAAAABAwwwwww0yAAAAAAAAAAAAAAAAAAEMwwwwwwwwwzCAAAAAAAAAAAAABAAwwwwwwwwwwwww4DAAAAAAAAABMIwwwwwwwwwwwwwwww00BAAAAAAAAwwwwwwwwwwwwwwwwwwww04CAAAEwwwwwwwwwwwwwwwwwwwwwwwwwwAIwwwwwwwwwwwwwwwwwwwwwwwwwwwzKwwwwwwwwwwwwwwwwwwwwwwwwwww8gwwwwwwwwwwwwwwwwwwwwwwwwwwww//xAAUEQEAAAAAAAAAAAAAAAAAAACQ/9oACAEDAQE/EFJ//8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAgEBPxBSf//EACoQAQABAgUDAwQDAQAAAAAAAAERADEhQEFQUWFxgTCRsRChwdEggPDh/9oACAEBAAE/EP6aWFHgxae3nX4pZwJ2FLavAUFq8hXzSKPVOqmudOiKuj7ChHEZ26eQcBdqR8Bd81dx9ExCTsxViacYqBYh/wAWoqZNTaglDqaD90qQl19aVuDdWanbiXVzaEleNA+MicaEqEsB4NmxF4ehzkzViyclKXISbIoiYDFadSzY4MpiLdfy2TADio8ZVjLqaQAxEk2OFFj/ANZbrHYgnLCaRldZctfdkTYruxSPfLzPINig5mXyPljYlh9XLrog+di+5cuMB4diGL1fGYsdthOPx+Ll74UEAbCUaRJ6ZfqYD77DO+haRElWXLiBESyUwWGGwEMuoMzKOMmw9bwzEk1xthEH3Zgw+n42GADDA98uhBKsFdKAbCEXimHfLyztb32NlLHx6OUBWAV6VBEDggoliary7GCAI3GiQ8Tg5OY/ydmQRGzUo6kyUfRnts/T8Mk5gSXzs/vBZFwboKAACxs/KFzvSIwkJkJBGBdpYWfsyE+zGzttLm0JHhPXQ+8uCgAAgMA2n7l8Vp6xoTES7V96+K09az3fO1fZNaetZ7vnavsGtPWs93ztTh+FWnrKR0W1GaccL1zxno/O0pzBq0miGA9dkYSpkQO4bNapE8S3vU8wNAsZEO4NSlQMuFqFADqOxRRDlawKTy4FXHjhgZWQFdKJBL/i1FyPRrnhcEeNamiB3GpMFyuZFERhNSsP8y/vWHngGamx8gqdPEv70qsrK57C/IBWG+Rb3oRJGRyuHD0P2qfNjQpihytWGk+TEoAQRsmRlQ9P9qlDZwJMp00ahwnyWoQChHU9UHFOgXqUJ6bXu7W9MBqrNRXlbPpMTBdakZ+Rd/VKrKyu3Ry7bp2rHg5G5/OU4lYXalZhoLG4lXBZKgYNDj+KIkNg/NOXUuu6TxOo16fXSAsctIjO7GIvL1OfogDgJe+7434THZ9OuC3hKriifallXneBgHG9f//Z";

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    public viewCtrl: ViewController,
    private toastCtrl: ToastController,
    private camera: Camera,
    public tinProv: TinderProvider,
    public imgProv: ImageProvider,
    private crop: Crop
  ) { }

  ionViewDidLoad() {

  }

  createProf() {
    this.tinUser._attachments = {
      profilePic: {
        content_type: 'image/jpeg',
        data: this.profilePicture.toString()
      }
    }
    this.tinUser.likedPeople = [];
    this.tinUser._id = this.tinUser.username;
    this.tinProv.create(this.tinUser);
    

    let toast = this.toastCtrl.create({
      message: 'Profile created succesfully',
      duration: 3000,
      position: 'bottom'
    });

    toast.present();

    this.viewCtrl.dismiss();
  }

  uploadPicture() {
    const options: CameraOptions = {
      destinationType: this.camera.DestinationType.DATA_URL,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      saveToPhotoAlbum: false
    }

    this.camera.getPicture(options).then((imageData) => {
      this.profilePicture = imageData;
    }, (err) => {
      console.log(err);
    })
  }

}
